apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-deployment
  labels:
    app: productservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: 'hardingtrutran/productservice:5b9874c'
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: postgres-cm
            - configMapRef:
                name: axon-cm
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: staging
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: productservice-svc
spec:
  selector:
    app: productservice
  ports:
    - port: 80
      targetPort: 8083
